//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrosvenorPracticum_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayTimeDishEntity
    {
        public int Id { get; set; }
        public bool IsMultiple { get; set; }
    
        public virtual DishEntity Dish { get; set; }
        public virtual DayTimeEntity DayTime { get; set; }
    }
}
