//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrosvenorPracticum_DAL.Models
{
    using System;
    using System.Collections.Generic;

    public partial class DishTypeEntity
    {
        public DishTypeEntity()
        {
            this.DishTypeDishEntities = new HashSet<DishTypeDishEntity>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string TypeId { get; set; }
    
        public virtual ICollection<DishTypeDishEntity> DishTypeDishEntities { get; set; }
    }
}
