//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrosvenorPracticum_DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodServiceModelContainer : DbContext, IFoodServiceModelContainer
    {
        public FoodServiceModelContainer()
            : base("name=FoodServiceModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<DishTypeEntity> DishTypeEntities { get; set; }
        public virtual IDbSet<DayTimeEntity> DayTimeEntities { get; set; }
        public virtual IDbSet<DishEntity> DishEntities { get; set; }
        public virtual IDbSet<DayTimeDishEntity> DayTimeDishEntities { get; set; }
        public virtual IDbSet<DishTypeDishEntity> DishTypeDishEntities { get; set; }
    }
}
